/**
 * generated by Xtext 2.12.0
 */
package org.xtext.project.turn.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class TurnQuickfixProvider extends XbaseQuickfixProvider {
}
