/**
 * generated by Xtext 2.14.0
 */
package org.xtext.project.turn.turn.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.project.turn.turn.Inclusion;
import org.xtext.project.turn.turn.InclusionFeature;
import org.xtext.project.turn.turn.TurnPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inclusion Feature</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.turn.turn.impl.InclusionFeatureImpl#getLinksSrc <em>Links Src</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InclusionFeatureImpl extends FeatureElementImpl implements InclusionFeature
{
  /**
   * The cached value of the '{@link #getLinksSrc() <em>Links Src</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinksSrc()
   * @generated
   * @ordered
   */
  protected EList<Inclusion> linksSrc;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InclusionFeatureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurnPackage.Literals.INCLUSION_FEATURE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Inclusion> getLinksSrc()
  {
    if (linksSrc == null)
    {
      linksSrc = new EObjectContainmentEList<Inclusion>(Inclusion.class, this, TurnPackage.INCLUSION_FEATURE__LINKS_SRC);
    }
    return linksSrc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TurnPackage.INCLUSION_FEATURE__LINKS_SRC:
        return ((InternalEList<?>)getLinksSrc()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TurnPackage.INCLUSION_FEATURE__LINKS_SRC:
        return getLinksSrc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TurnPackage.INCLUSION_FEATURE__LINKS_SRC:
        getLinksSrc().clear();
        getLinksSrc().addAll((Collection<? extends Inclusion>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TurnPackage.INCLUSION_FEATURE__LINKS_SRC:
        getLinksSrc().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TurnPackage.INCLUSION_FEATURE__LINKS_SRC:
        return linksSrc != null && !linksSrc.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InclusionFeatureImpl
