/*
 * generated by Xtext 2.14.0
 */
package org.xtext.project.turn.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.project.turn.parser.antlr.internal.InternalTurnParser;
import org.xtext.project.turn.services.TurnGrammarAccess;

public class TurnParser extends AbstractAntlrParser {

	@Inject
	private TurnGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTurnParser createParser(XtextTokenStream stream) {
		return new InternalTurnParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "URNspec";
	}

	public TurnGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TurnGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
