/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.project.turn.turn.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.project.turn.turn.Connect;
import org.xtext.project.turn.turn.EndPoint;
import org.xtext.project.turn.turn.EndpointWithConnect;
import org.xtext.project.turn.turn.TurnPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Endpoint With Connect</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.turn.turn.impl.EndpointWithConnectImpl#getRegularEnd <em>Regular End</em>}</li>
 *   <li>{@link org.xtext.project.turn.turn.impl.EndpointWithConnectImpl#getConnect <em>Connect</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EndpointWithConnectImpl extends RegularEndImpl implements EndpointWithConnect
{
  /**
   * The cached value of the '{@link #getRegularEnd() <em>Regular End</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegularEnd()
   * @generated
   * @ordered
   */
  protected EndPoint regularEnd;

  /**
   * The cached value of the '{@link #getConnect() <em>Connect</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnect()
   * @generated
   * @ordered
   */
  protected Connect connect;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EndpointWithConnectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurnPackage.Literals.ENDPOINT_WITH_CONNECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EndPoint getRegularEnd()
  {
    return regularEnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRegularEnd(EndPoint newRegularEnd, NotificationChain msgs)
  {
    EndPoint oldRegularEnd = regularEnd;
    regularEnd = newRegularEnd;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END, oldRegularEnd, newRegularEnd);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRegularEnd(EndPoint newRegularEnd)
  {
    if (newRegularEnd != regularEnd)
    {
      NotificationChain msgs = null;
      if (regularEnd != null)
        msgs = ((InternalEObject)regularEnd).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END, null, msgs);
      if (newRegularEnd != null)
        msgs = ((InternalEObject)newRegularEnd).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END, null, msgs);
      msgs = basicSetRegularEnd(newRegularEnd, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END, newRegularEnd, newRegularEnd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Connect getConnect()
  {
    return connect;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConnect(Connect newConnect, NotificationChain msgs)
  {
    Connect oldConnect = connect;
    connect = newConnect;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT, oldConnect, newConnect);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConnect(Connect newConnect)
  {
    if (newConnect != connect)
    {
      NotificationChain msgs = null;
      if (connect != null)
        msgs = ((InternalEObject)connect).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT, null, msgs);
      if (newConnect != null)
        msgs = ((InternalEObject)newConnect).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT, null, msgs);
      msgs = basicSetConnect(newConnect, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT, newConnect, newConnect));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END:
        return basicSetRegularEnd(null, msgs);
      case TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT:
        return basicSetConnect(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END:
        return getRegularEnd();
      case TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT:
        return getConnect();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END:
        setRegularEnd((EndPoint)newValue);
        return;
      case TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT:
        setConnect((Connect)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END:
        setRegularEnd((EndPoint)null);
        return;
      case TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT:
        setConnect((Connect)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TurnPackage.ENDPOINT_WITH_CONNECT__REGULAR_END:
        return regularEnd != null;
      case TurnPackage.ENDPOINT_WITH_CONNECT__CONNECT:
        return connect != null;
    }
    return super.eIsSet(featureID);
  }

} //EndpointWithConnectImpl
