/**
 * generated by Xtext 2.10.0
 */
package org.xtext.project.turn;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.xtext.project.turn.AbstractTurnRuntimeModule;
import org.xtext.project.turn.CommonValueConverter;
import org.xtext.project.turn.MyQNP;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TurnRuntimeModule extends AbstractTurnRuntimeModule {
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return MyQNP.class;
  }
  
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return CommonValueConverter.class;
  }
}
