/*
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.project.turn.ide


/**
 * Use this class to register ide components.
 */
class TurnIdeModule extends AbstractTurnIdeModule {
}
