/**
 * generated by Xtext 2.14.0
 */
package org.xtext.project.turn.turn;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature OR Decomposition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.turn.turn.FeatureORDecomposition#getDest <em>Dest</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.turn.turn.TurnPackage#getFeatureORDecomposition()
 * @model
 * @generated
 */
public interface FeatureORDecomposition extends EObject
{
  /**
   * Returns the value of the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dest</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dest</em>' containment reference.
   * @see #setDest(FeatureElement)
   * @see org.xtext.project.turn.turn.TurnPackage#getFeatureORDecomposition_Dest()
   * @model containment="true"
   * @generated
   */
  FeatureElement getDest();

  /**
   * Sets the value of the '{@link org.xtext.project.turn.turn.FeatureORDecomposition#getDest <em>Dest</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dest</em>' containment reference.
   * @see #getDest()
   * @generated
   */
  void setDest(FeatureElement value);

} // FeatureORDecomposition
