/**
 * generated by Xtext 2.14.0
 */
package org.xtext.project.turn.turn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>None Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project.turn.turn.TurnPackage#getNoneFeature()
 * @model
 * @generated
 */
public interface NoneFeature extends FeatureElement
{
} // NoneFeature
