/**
 * generated by Xtext 2.14.0
 */
package org.xtext.project.turn.turn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path Body Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project.turn.turn.TurnPackage#getPathBodyNode()
 * @model
 * @generated
 */
public interface PathBodyNode extends ReferencedBoundElement
{
} // PathBodyNode
