/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.project.turn.turn;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Referenced End</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project.turn.turn.TurnPackage#getReferencedEnd()
 * @model
 * @generated
 */
public interface ReferencedEnd extends EObject
{
} // ReferencedEnd
