/*
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.project.turn.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTurnValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.project.turn.turn.TurnPackage.eINSTANCE);
		return result;
	}
}
