/**
 * generated by Xtext 2.12.0
 */
package org.xtext.project.turn;

import org.xtext.project.turn.TurnStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TurnStandaloneSetup extends TurnStandaloneSetupGenerated {
  public static void doSetup() {
    new TurnStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
