/**
 * generated by Xtext 2.14.0
 */
package org.xtext.project.turn.turn.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.project.turn.turn.TurnPackage;
import org.xtext.project.turn.turn.URNmodelElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>UR Nmodel Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class URNmodelElementImpl extends MinimalEObjectImpl.Container implements URNmodelElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected URNmodelElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurnPackage.Literals.UR_NMODEL_ELEMENT;
  }

} //URNmodelElementImpl
